### ISSUE TITLE
Incorrect egui presentation on Wayland.

### ISSUE THREAD

**Issue by Vistavleal** [derivator/egui_vulkano#3]
OS: Arch linux 
DE: Plasma 5.22.5
CPU: 11th Gen Intel i5-1135G7 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]
session type: Wayland.

Example:
![Screenshot_20211012_231135](https://user-images.githubusercontent.com/26365890/137022902-080bd6f1-8d50-4e23-b749-3a2a5d66a18f.png)

Egui and vulcano individually work great. 
PS: Rust compiler complain that src/shaders/mod.rs can't find shaders.

**Comment by derivator** [comment]
Just to confirm, do you have [shaderc](https://archlinux.org/packages/extra/x86_64/shaderc/) installed?
