### ISSUE TITLE
update to Vulkano 0.28, winit 0.26, egui 0.16

### ISSUE THREAD

**Issue by VDorchester14** [derivator/egui_vulkano#6]
Hi, I've forked this repo for use in a personal project and managed to get the example running with Vulkano 0.28, winit 0.16, and egui 0.16. I figured I'd submit a PR just in case you or anyone else wanted to take a look.

**Comment by VDorchester14** [comment]
[Related PR](https://github.com/derivator/egui_vulkano/pull/7)

**Comment by derivator** [comment]
Thanks!
